name: backend-ci # TODO: change to your workflow name

on:  
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - 
        name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # TODO: change to your python version
      - 
        name: Install pipenv
        run: pip install pipenv
      - 
        name: Run tests
        working-directory: . # TODO: change to your pytest path
        run: |
          pipenv install --dev 
          pipenv shell
          pipenv run pytest -v backend/fastapiservice/test
        #   pipenv run coverage run -m pytest -v backend/fastapiservice/test
        #   pipenv run coverage report -m
        # pipenv install -r requirements.txt
        # To run the pytest without coverage report
        # pipenv run pytest -v .
